### PR TITLE
Bootstrap 4

### PR DESCRIPTION
**Pull request by dungmv**
https://github.com/mongo-express/mongo-express/pull/636

---
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/808)

### CODE REVIEW

**Comment by shakaran** [comment]
@dungmv could you rebase this PR with master so we can merge it? Thanks

**Comment by dungmv** [comment]
> @dungmv could you rebase this PR with master so we can merge it? Thanks

@shakaran ok, I'll rebase weekend

**Comment by shakaran** [comment]
@dungmv any chance to get this rebased or updated with Bootstrap 5?

**Comment by shakaran** [comment]
Closing in favor of superseeded #1394

**Pull request closed without merging**
