### PR TITLE
Update mongodb to v4

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857)
---

### CODE REVIEW

**Review by BlackthornYugen — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857#-:-N9l_ANFBRFz6-O759tX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Review by rtritto — COMMENTED** [review]
Added a commit to update yarn.lock and mongobd dependency version.

> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857#-:-N9mjgMq3K8z3aorRlgN:b-67taq2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Review by BlackthornYugen — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Review by BlackthornYugen — APPROVED** [review]
Maybe [this test](https://github.com/mongo-express/mongo-express/blob/cae4e627fdcb9082e6b2f6a0573491b7357aed49/test/lib/csvSpec.js#L24-L28) isn't valid for Mongo 4.x.x? Maybe a.a now gives a string instead of an ObjectId type? 

```
  1) CSV
       should handle mongo ObjectID:

      AssertionError: expected '"a.a"\n"111111111111111111111111"' to deeply equal '"a.a"\n"ObjectId(""111111111111111111111111"")"'
      + expected - actual

       "a.a"
      -"111111111111111111111111"
      +"ObjectId(""111111111111111111111111"")"
      
      at test (test/lib/csvSpec.js:8:24)
      at Context.<anonymous> (test/lib/csvSpec.js:27:5)
      at process.processImmediate (node:internal/timers:471:21)
```

> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857#-:-NA26LfbD3-pZQTWzIYf:bhbz7hy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Comment by rtritto** [comment]
@BlackthornYugen ObjectID is deprecated, I did a commit to replace it with ObjectId.

**Review by BlackthornYugen — APPROVED** [review]
👍

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857#-:-NA5SiBX1hAeWFlg7KR_:b44tpx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Comment by rtritto** [comment]
Need reviews

**Review by BlackthornYugen — APPROVED** [review]
👍

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/857#-:-NAEaw0i5KliscDkqkvS:b44tpx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Comment by rtritto** [comment]
@BlackthornYugen Click to open document is not working. Should this merge be reverted?

**Comment by BlackthornYugen** [comment]
Yup, let's make a new PR.

**Comment by rtritto** [comment]
FYI: I have this [branch](https://github.com/rtritto/mongo-express/tree/develop-copy0) where some changes and mangodb v4 correctly works.

**Comment by BlackthornYugen** [comment]
Doesn't look like I can revert from my phone.  Will be on a laptop in about 45 minutes

**Comment by BlackthornYugen** [comment]
> FYI: I have this [branch](https://github.com/rtritto/mongo-express/tree/develop-copy0) where some changes and mongodb v4 correctly works.

Could it have been one of the other dependencies that were updated that caused the issue?

**Comment by rtritto** [comment]
I'm almost fixed problems; I can do another PR to fix all them (no merge revert needed).

> Could it have been one of the other dependencies that were updated that caused the issue?

I changed callbacks with async/await and it's working (I think that mongodb v4 removed some callback support).

**Pull request merged**
