### PR TITLE
chore! update mongodb to v6

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/1289)
- - -

### Utilities
- [Changelog MongoDB v6](https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0)
- [Changelog bson v6](https://github.com/mongodb/js-bson/releases/tag/v6.0.0)

### TODO
- [x] update `bson` to v6
- [x] update `mongodb-query-parser` version to a compatible _bson v6_ one (v4?) --> https://github.com/mongodb-js/query-parser/issues/138
  - [x] workaround to #1249: `mongodb-query-parser` v4.0.0 is patched in [rtritto/query-parser#4.0.0-fix-bindata](https://github.com/rtritto/query-parser/tree/4.0.0-fix-bindata)
- [x] replace _collection.stats_ function with _$collStats_ (aggregation)
- [x] replace _SSL_ options with _TLS_ options (related #1203)
  - [x] rename options:
    - `ssl` --> `tls` (***it can be reverted***)
    - `sslValidate` --> `tlsAllowInvalidCertificates`
    - `sslCA` --> `tlsCAFile`
  - [x] rename env vars:
    - `ME_CONFIG_MONGODB_SSL` --> `ME_CONFIG_MONGODB_TLS` (***it can be reverted***)
    - `ME_CONFIG_MONGODB_SSLVALIDATE` --> `ME_CONFIG_MONGODB_TLS_ALLOW_CERTS`
    - `ME_CONFIG_MONGODB_CA_FILE` --> `ME_CONFIG_MONGODB_TLS_CA_FILE`
- [x] add _TLS_ certificate options (replace #1203)
  - `ME_CONFIG_MONGODB_TLS_CERT_FILE`
  - `ME_CONFIG_MONGODB_TLS_CERT_KEY_FILE`
  - `ME_CONFIG_MONGODB_TLS_CERT_KEY_FILE_PASSWORD`
- [x] _compact_ command in `db.command` (used by `/lib/routes/collection.js`) isn't removed ([source](https://www.mongodb.com/docs/manual/reference/command))
- [x] tests
  - [x] `should convert BinData to string` --> source: https://github.com/mongodb/js-bson/issues/602 --> ***need help***
- [x] Minimum Node version 16.20.1

Close: #1203

### CODE REVIEW

**Comment by rtritto** [comment]
@daniel-sc please can you update the test "should convert BinData to string" that you wrote in #1254 to support _bson_ v6 (string format is removed from _Binary_)?

**Comment by daniel-sc** [comment]
> @daniel-sc please can you update the test "should convert BinData to string" that you wrote in #1254 to support _bson_ v6 (string format is removed from _Binary_)? Maybe changes in test of [mongodb/js-bson#602](https://github.com/mongodb/js-bson/pull/602) can help.

@rtritto how would you like that - I probably have no write access to this branch?

Probably the change would be straight forward:

old:
```ts
const test = { bin: new bson.Binary('test', 80) };
```
new:
```ts
const test = { bin: new bson.Binary(new TextEncoder().encode('test'), 80) };
```

**Comment by rtritto** [comment]
Thanks, I did the commit.

**Comment by rtritto** [comment]
FYI @shakaran @BlackthornYugen

**Pull request merged**
