### PR TITLE
Add Unauthenticated healthcheck

### LINKED ISSUE #849: Feature Request: Unauthenticated health check
For certain deployments, e.g. Kubernetes with CGE Load Balancers, each pod is required to provide an unauthenticated health check route. This route ("/" by default, but I think it can be configured) should responds with status code `200 OK` when the service is running properly.

Currently, `mongo-express` only supports this requirement if basic auth is disabled, which then leaves it completely unauthenticated.

I propose an additional parameter `ME_CONFIG_HEALTH_CHECK_PATH`, which creates an unauthenticated route that simply returns `200 OK` when called. The fact that the route can be called should suffice as a health check, although more elaborate ones could also be implemented.

Ideally this route should work in combination with `ME_CONFIG_SITE_BASEURL`, such that the following scenario would be possible:

- `ME_CONFIG_SITE_BASEURL = "/express"` -> The mongo-express UI is served on "/express"
- `ME_CONFIG_HEALTH_CHECK_PATH = "/"` -> Health checks can be run on "/"

### PR DESCRIPTION
**Pull request by MahdiAbbasi95**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/940)
- - -

Hi,
I've added the unauthenticated health check due to the issue #849.

Resolves #849

### CODE REVIEW

**Review by BlackthornYugen — APPROVED** [review]
Thanks for the PR! :lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/940#-:-NBZ30zp3sGf9bQ_WN7n:b-k5hw6d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MahdiAbbasi95)

**Review by BlackthornYugen — COMMENTED** [review]
Oh, test failures though, :lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/940#-:-NBZ3QI10g7BjLzfG1JQ:b-9ae4n9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MahdiAbbasi95)

**Comment by rtritto** [comment]
_/test/testDefaultConfig.js_ needs something like:
```js
...
healthCheck: {
  path: '/status',
}
...
```

**Comment by shakaran** [comment]
@MahdiAbbasi95 could you update the test for pass the CI?

**Comment by MahdiAbbasi95** [comment]
> @MahdiAbbasi95 could you update the test for pass the CI?

I've updated the test.

**Comment by MahdiAbbasi95** [comment]
> > @MahdiAbbasi95 could you update the test for pass the CI?
> 
> I've updated the test.

The last job has been failed due to the lint issues. I'll fix them.

**Comment by MahdiAbbasi95** [comment]
> > > @MahdiAbbasi95 could you update the test for pass the CI?
> > 
> > 
> > I've updated the test.
> 
> The last job has been failed due to the lint issues. I'll fix them.

@BlackthornYugen  I've fixed the issues, could you retry the job please?

**Review by shakaran — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/940#-:-NBcxueu3saLTBM-5HDh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MahdiAbbasi95)

**Pull request merged**
