### PR TITLE
release: v1.1.0-rc-1

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/1653)

### CODE REVIEW

**Comment by rtritto** [comment]
After this is merged, I will try to run the release workflow using GitHub.

**Review by BlackthornYugen — APPROVED** [review]

**Comment by rtritto** [comment]
https://github.com/mongo-express/mongo-express/actions/runs/11573703559/job/32216372153
```console
npm error code ENEEDAUTH
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`
```

`NPM_TOKEN` with token needs to be added as repository secret.

FYI @xTudoS @BlackthornYugen @shakaran @dozoisch

**Comment by rtritto** [comment]
@dozoisch any update?

**Comment by rtritto** [comment]
I sent an email to @dozoisch

**Pull request merged**
