### PR TITLE
#214 added a setting that can disable console logs 

### PR DESCRIPTION
**Pull request by GreenPioneer**
* added config to defaults
* add if check console check to db.js & app.js
* deleted extra commas in the config.default.js

### CODE REVIEW

**Comment by GreenPioneer** [comment]
let me know your thoughts and if i missed anything

**Comment by wulfsolter** [comment]
Would you mind re-adding the trailing commas on `config.default.js` such as https://github.com/mongo-express/mongo-express/pull/216/commits/8a36fb7b1b2a30058bae46bf51ea8f5365f0397f#diff-9d61188cf4dfc9367c274b42b9aef2f5L27 as they're part of of ECMAScript specs these days. Good overview on [StackOverflow](https://stackoverflow.com/questions/7246618/trailing-commas-in-javascript#7246662)

If you install devDependencies ( `npm install --dev`) it should enable styleguide checking with JSCS ;)

**Comment by GreenPioneer** [comment]
Added them back .

**Comment by GreenPioneer** [comment]
I didnt know that , thats really interesting . Thanks for the good info

**Comment by wulfsolter** [comment]
Still failing on styleguide rules.

> If you install devDependencies ( npm install --dev) it should enable styleguide checking with JSCS ;)

**Comment by GreenPioneer** [comment]
Yea sorry about failing twice on that i assumed when i changed back that it would just work.... and thats what i get for assuming. let me know if i need todo anything else

**Comment by wulfsolter** [comment]
Yeah, sorry. It was quite the battle in my head - do I just fix the handful of spaces myself, or ask you to install dev dependencies. I went with devDep because it's one of the first things that should be done when about to modify some upstream, hopefully this will save you more time in the long run :)

Anyway... merged, version bumped, pushed to npm. Thanks man!

**Comment by GreenPioneer** [comment]
Yea i like it and will def use it in the future if i push any thing else

**Comment by GreenPioneer** [comment]
thanks again

**Pull request merged**
