### PR TITLE
Support for collection view showing UUIDs and searches allowing UUIDs (BinData type 4)

### PR DESCRIPTION
**Pull request by shadowbane1000**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/552)
---

This is a set of changes continuing on with the other changes that have been done for UUID support for IDs.  Specifically when a UUID is used for the _id field.  I only use BinData type 4 for my UUIDs, so that was all that I implemented and tested.

These changes make the list of documents in a collection show the UUIDs as human readable strings, rather than as base64 data.  These changes also support searching for documents by a UUID.

Please let me know what the minimal additional changes are that you would require to allow this to be pulled in to master.

Thanks

## TODO
- [x] Add hyphens to UUID in document detail (related https://github.com/mongodb-js/query-parser/issues/115)
  - Patched with `patch-package`
- [x] Handle new UUID with `UUID()` or `new UUID()` (related bug https://github.com/mongodb-js/query-parser/issues/114)
  - Patched with `patch-package`
- [x] Add unit tests

### CODE REVIEW

**Comment by dpacierpnik** [comment]
Nobody interested in merging this feature? It's really useful. We just stopped using this tool, because it doesn't work correctly with UUIDs.

**Comment by paulpmi** [comment]
same here planning to drop express due to this limitation

**Review by shakaran — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/552#-:-NBnF0230Yx0UbbxaOoA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BlackthornYugen)

**Comment by rtritto** [comment]
_README_ needs the _UUID_ in BSON types.

**Comment by shakaran** [comment]
> _README_ needs the _UUID_ in BSON types.

Would you need to add it or this PR is finished?

**Comment by shakaran** [comment]
> @shakaran I updated the README.
> 
> Currently only work: `UUID(<uuid>)` or `new UUID(<uuid>)`. To generate new UUID `UUID()` or `new UUID()`, there is the bug [mongodb-js/query-parser#114](https://github.com/mongodb-js/query-parser/issues/114).
> 
> I'm fixing another bug on _loadDocument_ where the `UUID(<uuid>)` is displayed with no hyphens.

Nice work. Please could you add unit tests for this cases so we ensure the same behaviour for future versions? Thanks, great work

**Comment by shakaran** [comment]
:lgtm waiting review from @BlackthornYugen

**Comment by rtritto** [comment]
I want add more unit tests.
With `UUID(<uuid>)`, should we valide the uuid value? (`mongodb-query-parser` don't check)
If yes, with `UUID()` we can also generate new uuid and replace it with `UUID(<uuid>)`.

I need some help to find where add hyphens to uuid in document detail.

**Review by BlackthornYugen — APPROVED** [review]
> Reviewed 4 of 5 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/552)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Comment by rtritto** [comment]
In document list, I changed the _id output format from `UUID(<uuid>)` to `<uuid>` (such as ObjectId).

Now I'm searching for TODO `Add hyphens to uuid in document detail`.

**Comment by rtritto** [comment]
TODO `Add hyphens to uuid in document detail` is related to toJSString (https://github.com/mongodb-js/query-parser/issues/115)

**Comment by rtritto** [comment]
@shakaran I can reintroduce [patch-package](https://www.npmjs.com/package/patch-package) to patch manually the 2 dependecy of 2 opened issues.
Last step is to add unit tests for the UUID() and UUID(<uuid>) cases.
If you agree, I can proceed.

PS: after updating to yarn berry, we can remove `patch-package` dependency (there is _patch_ command included in yarn berry).

**Comment by rtritto** [comment]
TODO is completed.

FYI @shakaran @BlackthornYugen

**Review by shakaran — APPROVED** [review]

**Pull request merged**
