### PR TITLE
feature: disable node 12 and enable node 18 support

### PR DESCRIPTION
**Pull request by shakaran**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/914)

### CODE REVIEW

**Comment by shakaran** [comment]
Interesting, build fail in custom fork of renderjson

With only one commit ahead of change and 8 commits behind

https://github.com/caldwell/renderjson/compare/master...dozoisch:renderjson:master

Which is https://github.com/caldwell/renderjson/commit/cd0ef870c1298d53f09555da54e4bf57a0d21414

So maybe we can bump to use https://github.com/caldwell/renderjson and if needed make a patch or see if works properly

**Comment by rtritto** [comment]
Maybe https://github.com/caldwell/renderjson/pull/40 is needed.

**Review by BlackthornYugen — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/914)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shakaran)

**Comment by shakaran** [comment]
@rtritto @BlackthornYugen issues fixed with yarn. Ship it! Node 18 :love_letter:

**Pull request merged**
