### PR TITLE
Update json2csv to v5

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)
- - -

https://github.com/zemirco/json2csv#upgrading-from-3x-to-4x

https://github.com/zemirco/json2csv#upgrading-from-4x-to-5x

NOTE: added static EOL (\n)

### CODE REVIEW

**Review by rtritto — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Review by BlackthornYugen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 1 unresolved discussion (waiting on @rtritto)

___
*[`lib/csv.js` line 2 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzcdz0z5tlfFchPlt:-NBfzcdz0z5tlfFchPlu:b-u2zea6) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L2)):*
> ```JavaScript
> import flat from 'flat';
> import { parse as csv } from 'json2csv';
> ```

This looks a bit weird

**Review by BlackthornYugen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 2 unresolved discussions (waiting on @rtritto)

___
*[`lib/csv.js` line 21 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzpR151vczJspH4tv:-NBfzpR151vczJspH4tw:b-p7uix0) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L21)):*
> ```JavaScript
>     data[i] = flat(current, { safe: true });
>   }
>   return csv(data, { eol: '\n' });
> ```

What about csv.parse(data, { eol: '\n'});?

**Review by rtritto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen)

___
*[`lib/csv.js` line 2 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzcdz0z5tlfFchPlt:-NBg-nk4BktO6o_nbFry:b-896fix) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L2)):*
<details><summary><i>Previously, BlackthornYugen (John Steel) wrote…</i></summary><blockquote>

This looks a bit weird
</blockquote></details>

Done.
___
*[`lib/csv.js` line 21 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzpR151vczJspH4tv:-NBg-_hW8PXwUmwhWvWA:b-9u7acc) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L21)):*
<details><summary><i>Previously, BlackthornYugen (John Steel) wrote…</i></summary><blockquote>

What about csv.parse(data, { eol: '\n'});?
</blockquote></details>

Change to json2csv.parse?

**Review by BlackthornYugen — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 2 unresolved discussions (waiting on @rtritto)

___
*[`lib/csv.js` line 2 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzcdz0z5tlfFchPlt:-NBg0l0kBvIgWFmiaVci:bg7igkv) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L2)):*
<details><summary><i>Previously, rtritto wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:lgtm: 
___
*[`lib/csv.js` line 21 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzpR151vczJspH4tv:-NBg0oa1Dqc3im1an5EK:bg7igkv) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L21)):*
<details><summary><i>Previously, rtritto wrote…</i></summary><blockquote>

Change to json2csv.parse?
</blockquote></details>

:lgtm:

**Review by rtritto — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 2 unresolved discussions (waiting on @rtritto)

**Review by rtritto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen and @rtritto)

___
*[`lib/csv.js` line 2 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzcdz0z5tlfFchPlt:-NBg1SPr3bZNi_FFUfO7:b-896fix) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L2)):*
<details><summary><i>Previously, BlackthornYugen (John Steel) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

Done.

**Review by rtritto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: all files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen)

___
*[`lib/csv.js` line 21 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzpR151vczJspH4tv:-NBg1Ucb6LzZhPBf0Vaw:b-896fix) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L21)):*
<details><summary><i>Previously, BlackthornYugen (John Steel) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

Done.

**Review by BlackthornYugen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/950)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

___
*[`lib/csv.js` line 2 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzcdz0z5tlfFchPlt:-NBg1h6vCqzDPGgpxYS7:bb6un1j) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L2)):*
<details><summary><i>Previously, rtritto wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done
___
*[`lib/csv.js` line 21 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/950#-NBfzpR151vczJspH4tv:-NBg1jXC9LvejU7FRx-X:bb6un1j) ([raw file](https://github.com/mongo-express/mongo-express/blob/0a84e319dd7465516aa187336582d497047dab30/lib/csv.js#L21)):*
<details><summary><i>Previously, rtritto wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done

**Pull request merged**
