### PR TITLE
feat: support aggregate query in advanced tab

### LINKED ISSUE #438: Is join ($lookup) supported in some way?
I need to do a join between two collections.
I wrote a query with a $lookup, but it doesn't find anything. That is probably because $lookup needs to work within aggregate(), not find().

Is there any plan to support such functionality?

Thanks!

### PR DESCRIPTION
**Pull request by armellarcier**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/859)
---

with checkbox opt-in

closes #438 ref https://github.com/mongo-express/mongo-express/issues/81

image

### CODE REVIEW

**Comment by armellarcier** [comment]
@dozoisch pagination works, as well as query formatting errors

**Review by c58 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @armellarcier)

**Comment by armellarcier** [comment]
@c58 is this ok ?

**Comment by c58** [comment]
@armellarcier yep, LGTM, i'm not sure who can merge it though, i dont have a button for that

**Comment by shakaran** [comment]
@armellarcier could you rebase resolving the conflicts, so we can merge it soon?

**Comment by BlackthornYugen** [comment]
@armellarcier thanks for the PR, I'd be happy to merge once it's rebased :)

**Review by BlackthornYugen — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/859#-:-NApYrMU2uQXBuVabh-b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @armellarcier)

**Comment by armellarcier** [comment]
@BlackthornYugen @c58 I did rebase this branch. Was not easy but I'm happy to see the code getting more clear and concise on master.
I tested the code manually but a new review is necessary.

**Review by BlackthornYugen — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/859)* status: all files reviewed, 1 unresolved discussion (waiting on @armellarcier)

___
*[`lib/views/collection.html` line 134 at r2](https://reviewable.io/reviews/mongo-express/mongo-express/859#-NB8xJs397KZywa6r9Ll:-NB8xJs397KZywa6r9Lm:b-jlbbon) ([raw file](https://github.com/mongo-express/mongo-express/blob/4764213fd01d780504428cb4a532d9b4f249c407/lib/views/collection.html#L134)):*
> ```HTML
>             </div>
>             <div class="row">
>             <button style="height:120px;" type="submit" class="btn btn-primary btn-block">
> ```

Was resizing the submit button height intentional?

**Review by BlackthornYugen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/859)* status: all files reviewed, 1 unresolved discussion (waiting on @armellarcier)

___
*[`lib/views/collection.html` line 134 at r2](https://reviewable.io/reviews/mongo-express/mongo-express/859#-NB8xJs397KZywa6r9Ll:-NB8y3QE6Qa5WQvScn-5:b-2fnje2) ([raw file](https://github.com/mongo-express/mongo-express/blob/4764213fd01d780504428cb4a532d9b4f249c407/lib/views/collection.html#L134)):*
<details><summary><i>Previously, BlackthornYugen (John Steel) wrote…</i></summary><blockquote>

Was resizing the submit button height intentional?
</blockquote></details>

Oh right! The checkbox is above the button. I thought it was on the side. Looks good!

**Review by BlackthornYugen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @armellarcier)

**Pull request merged**
