### PR TITLE
Add collection column sorting

### PR DESCRIPTION
**Pull request by knickers**
This adds sorting to collections as requested in #235. Just click the column headers to toggle between ascending and descending sort order.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Wowowow! 👍 Can you please add a screenshot with this change? I'm too lazy to test it right now but I'm curious to see it in action.

**Comment by knickers** [comment]
These images show unsorted, ascending, and descending sorting of the `videoId` column.

"unsorted" screenshot from 2016-06-25 14-01-48

"ascending" screenshot from 2016-06-25 14-02-38

"descending" screenshot from 2016-06-25 14-03-00

**Comment by IonicaBizau** [comment]
@knickers Amazing! ✨ Is it possible to sort by two columns?

E.g (sorted by both columns, second one having priority):

| First name | Last name |
|------------|-----------|
| Alice      | Anderson  |
| Carol       | Anderson  |
| Bob      | Smith     |

In fact, the whole point is to send to Mongo both sorting fields—probably passing an array like `[["name.first", 1], ["name.last", 1]]` (to be checked, I'm not sure if this still works). 😄

**Comment by knickers** [comment]
Yes, you can sort any number of columns, although I'm not sure in what order they are prioritized. Probably left-to-right at the moment.

**Comment by knickers** [comment]
Hey @wulfsolter, can you take a look at this? I would like a second opinion before merging it.

**Comment by wulfsolter** [comment]
Holla @knickers ! Sorry, got horridly snowed under with work for a while there, it's a long time getting back on top of things. Looks good, real good :)

**Pull request merged**
