### PR TITLE
Fixing #237

### PR DESCRIPTION
**Pull request by heartnetkung**
screenshot from 2016-10-27 17 15 45

## Pull Request Overview
1. add export to csv button
2. use this package `https://github.com/zemirco/json2csv` to convert JSON array to CSV
  - my reason to choose this lib is that it has a lot of stars, it handles multiple schema well, and it handles nested array well
3. special stringify function for ObjectID objects
4. test cases are added to ensure compatibility since csv conversion is can be tricky especially in edge cases
5. there should be no lint issue this time ;)

### CODE REVIEW

**Comment by dozoisch** [comment]
Awesome!  That looks good!  I'll try it today and merge it!

Thanks!

**Comment by heartnetkung** [comment]
Glad I could be of help XD

By the way, I'm planning on fixing #258 as well. Not really sure how the UI should be. Any ideas?

**Comment by dozoisch** [comment]
Hmm! Very good question! If I come up with ideas, I'll let you know.

**Comment by dozoisch** [comment]
@heartnetkung lets continue the talk about 258 in 258!

**Pull request merged**
