### PR TITLE
Remove Bluebird and replace callbacks with async/await

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/884)
- - -

Remove callbacks for #857

### CODE REVIEW

**Review by BlackthornYugen — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/884)* status: all files reviewed, 1 unresolved discussion (waiting on @rtritto)

___
*[`lib/routes/database.js` line 60 at r1](https://reviewable.io/reviews/mongo-express/mongo-express/884#-NAFzH6339wStLOsEcBC:-NAFzH6339wStLOsEcBD:byfynxl) ([raw file](https://github.com/mongo-express/mongo-express/blob/b00ce5b9705761cb32d85a9550a61000897620c4/lib/routes/database.js#L60)):*
> ```JavaScript
>       });
> 
>       // await ndb.dropCollection('delete_me').then(() => {
> ```

Can we delete the commented code?

**Comment by rtritto** [comment]
I don't know, there should be some reason.

**Review by BlackthornYugen — APPROVED** [review]
In general I'd try to avoid keeping commented code arround but since it was there before your change I guess it's okay. 😛

> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/884#-:-NAGSKis167a4ssl72EA:b-rbqule)* status: all files reviewed, 1 unresolved discussion (waiting on @rtritto)

**Review by BlackthornYugen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/884)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Pull request merged**
