### PR TITLE
Bump bson 6.5.0

### PR DESCRIPTION
**Pull request by xTudoS**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/1488)
- - -

Bumps [bson](https://github.com/mongodb/js-bson) from 6.4.0 to 6.5.0.
- [Release notes](https://github.com/mongodb/js-bson/releases)
- [Changelog](https://github.com/mongodb/js-bson/blob/main/HISTORY.md)
- [Commits](https://github.com/mongodb/js-bson/compare/v6.4.0...v6.5.0)

---
updated-dependencies:
- dependency-name: bson dependency-type: direct:production update-type: version-update:semver-minor ...

updated-tests:
- bsonSpecs.ts

To this PR I followed tests from official repo: https://github.com/mongodb/js-bson/tree/main/test/node/parser
I know mongo-express do parser with another lib, but I once BSON already do this, we can move to it soon if it don't break anything.

This PR closes: https://github.com/mongo-express/mongo-express/pull/1462

### CODE REVIEW

**Comment by xTudoS** [comment]
@rtritto @shakaran Would you guys mind in review this PR please?

**Comment by rtritto** [comment]
> I know mongo-express do parser with another lib, but I once BSON already do this, we can move to it soon if it don't break anything.

Which replace do you mean?

**Comment by xTudoS** [comment]
> > I know mongo-express do parser with another lib, but I once BSON already do this, we can move to it soon if it don't break anything.
> 
> Which replace do you mean?

instead of using 

`import parser, { toJSString } from 'mongodb-query-parser';
`

that is in here: https://github.com/mongo-express/mongo-express/blob/master/lib/bson.js

use  BSON.serialize and BSON.deserialize from bson lib like in the tests:

https://github.com/mongodb/js-bson/blob/d7898f9907d389e5bb40d5b52664a1ff341b49b5/test/node/parser/deserializer.test.ts#L8

**Comment by xTudoS** [comment]
> > > I know mongo-express do parser with another lib, but I once BSON already do this, we can move to it soon if it don't break anything.
> > 
> > 
> > Which replace do you mean?
> 
> instead of using
> 
> `import parser, { toJSString } from 'mongodb-query-parser'; `
> 
> that is in here: https://github.com/mongo-express/mongo-express/blob/master/lib/bson.js
> 
> use BSON.serialize and BSON.deserialize from bson lib like in the tests:
> 
> https://github.com/mongodb/js-bson/blob/d7898f9907d389e5bb40d5b52664a1ff341b49b5/test/node/parser/deserializer.test.ts#L8

but I didn't it in this PR, in here I just updated the tests following the tests on original bson repo
this replacement is subject for another PR

**Review by shakaran — APPROVED** [review]

**Pull request merged**
