### PR TITLE
express 5 compatability

### PR DESCRIPTION
**Pull request by razvikel**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/490)
---

Fixed query modification for `express 5` compatability.

### CODE REVIEW

**Comment by rtritto** [comment]
Fix valid RegExp ([source](https://expressjs.com/en/guide/migrating-5.html)):
```console
Matching group expressions are only RegExp syntax.
(*) is no longer valid and must be written as (.*), for example.
```

`/lib/router.js`
```diff
// View helper, sets local variables used in templates
-  appRouter.all('*', async function (req, res, next) {
+  appRouter.all('(.*)', async function (req, res, next) {
    res.locals.baseHref       = buildBaseHref(req.originalUrl, req.url);
    res.locals.databases      = mongo.getDatabases();
    res.locals.collections    = mongo.collections;
    res.locals.gridFSBuckets  = utils.colsToGrid(mongo.collections);
```

**Comment by shakaran** [comment]
@razvikel could you reconsider rebase and resolve the conflicts for this Pull Request? Thanks

**Comment by rtritto** [comment]
Please move this PR to Draft.
We need a stable v5 (v5-not-stable is not synched with v4)

**Comment by shakaran** [comment]
For reference: https://expressjs.com/en/guide/migrating-5.html

**Comment by rtritto** [comment]
You're right.
_query_ object is not replaced. We can remove line:
```diff
...
exp.viewCollection = function (req, res) {
- req.query = req.query || {}; // might not be present in Express5
...
```
This fix works for both versions.

**Comment by rtritto** [comment]
@BlackthornYugen replaced by #925, can be closed

**Comment by BlackthornYugen** [comment]
Covered in #925

**Pull request closed without merging**
