### PR TITLE
Rearranged Index Screen - Cosmetic Changes

### PR DESCRIPTION
**Pull request by Manish2005**
Cosmetic Changes - 
Rearranged components on index screen to improve accessibility and looks

- Converted Databases div into panel
- Converted Server Status div into panel
- Moved Create Database form to top

Attaching screenshot for the same, 
[http://i.imgur.com/XiYhblA.png]

### CODE REVIEW

**Comment by wulfsolter** [comment]
Looks good, thanks heaps! Mind updating README.md to updated screenshot?

**Comment by Manish2005** [comment]
We currently don't have the index page screenshot in the README file. Shall I add it?

**Comment by wulfsolter** [comment]
Please :)

**Comment by Manish2005** [comment]
Done. :)

**Pull request merged**
