### PR TITLE
Add environment value for baseUrl config value

### PR DESCRIPTION
**Pull request by joshperry**
This will significantly ease mounting at a subpath using the virgin dockerhub image.

### CODE REVIEW

**Comment by wulfsolter** [comment]
Nice one! Thanks @joshperry 

Published to npm

**Comment by joshperry** [comment]
Thanks for the merge, @wulfsolter. I noticed there was a discussion on a continuous build to dockerhub. Did that get finished up? I'm using knickers/mongo-express.

**Comment by wulfsolter** [comment]
I'm not using Docker in prod so not 100% certain on best way to go about this. You familiar with Travis or have set up such systems?  Would be good to save @knickers having to rebuild things all the time.

**Comment by knickers** [comment]
We've made a pull request to the docker official images, just waiting on review now. https://github.com/docker-library/official-images/pull/1471

**Comment by wulfsolter** [comment]
Legend! :)

On Thu, Mar 10, 2016 at 4:12 PM, Nick Cox <notifications@github.com> wrote:

> We've made a pull request to the docker official images, just waiting on
> review now. docker-library/official-images#1471
> <https://github.com/docker-library/official-images/pull/1471>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mongo-express/mongo-express/pull/199#issuecomment-194640481>
> .
>



-- 
--
Wulf Solter
+64 21 294 1295 <+64212941295>
http://wulf.co.nz

**Comment by knickers** [comment]
P.S. docker hub does all the rebuilding automatically, I don't have to do anything :wink:.

**Comment by joshperry** [comment]
Ah rad! Thanks guys!

**Pull request merged**
