### PR TITLE
added sanitizing for file input

### LINKED ISSUE #980: Vulnerability Scanner Found unsanitized input in collection.js
Ran a new scan and found an XSS attack vector, think I have a solution will create PR
mongo-express-vuls

### PR DESCRIPTION
**Pull request by OOCAZ**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981)
- - -

Fix #980 

Let me know if we need to do something else
---
Additional changes:
- replace `escapeHtml.js` with `html-entities`

### CODE REVIEW

**Review by BlackthornYugen — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981#-:-NCRI3S658j6rlKSfrZS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OOCAZ)

**Comment by BlackthornYugen** [comment]
Where does escapeHtlm come from?

**Review by BlackthornYugen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981)* status: all files reviewed, 1 unresolved discussion (waiting on @OOCAZ)

*[a discussion](https://reviewable.io/reviews/mongo-express/mongo-express/981#-NCRO8346skUOuiyzGcM:-NCRO8346skUOuiyzGcN:b7p0bfe) (no related file):*
Can we import this function explicitly?

___

**Comment by OOCAZ** [comment]
> > _[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981)_ status: all files reviewed, 1 unresolved discussion (waiting on @OOCAZ)
> 
> _[a discussion](https://reviewable.io/reviews/mongo-express/mongo-express/981#-NCRO8346skUOuiyzGcM:-NCRO8346skUOuiyzGcN:b7p0bfe) (no related file):_ Can we import this function explicitly?

yes and no, I thought it was just built in, but apparently not, found an npm based library that is used in almost everything else: https://www.npmjs.com/package/escape-html I will change the function if someone else can handle the yarnfile when I get the function change pushed

**Comment by rtritto** [comment]
@OOCAZ I use [html-entities](https://www.npmjs.com/package/html-entities), it's maintained.

**Comment by OOCAZ** [comment]
> @OOCAZ I use [html-entities](https://www.npmjs.com/package/html-entities), it's maintained.

that works, i'm not picky, you want to make the changes?

**Comment by rtritto** [comment]
> that works, i'm not picky, you want to make the changes?

Yes

**Comment by rtritto** [comment]
We need also replace the `escapeHtml` file with `html-entities`.

FYI @BlackthornYugen

**Review by BlackthornYugen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen, @OOCAZ, and @rtritto)

___
*[`lib/routes/collection.js` line 535 at r3](https://reviewable.io/reviews/mongo-express/mongo-express/981#-NCRdjLV5iSXgFDNtS8t:-NCRdjLWA9p_mhhc4710:brdy2kd) ([raw file](https://github.com/mongo-express/mongo-express/blob/438f5339d8c116cb76e4356342b596851066ed62/lib/routes/collection.js#L535)):*
> ```JavaScript
> 
>     for (const file of files) {
>       const fileContent = encode(file.data.toString('utf8'));
> ```

Can we import the whole namespace? Or import it as escapeHtml? Encode isn't very descriptive.

**Comment by rtritto** [comment]
@BlackthornYugen should be OK.
@OOCAZ please do some smoke tests.

PS: @OOCAZ please be careful when change dependencies; accidentally create _package-lock.json_ and change all content of _yarn.lock_.

**Comment by OOCAZ** [comment]
did some initial testing and this appears to work @rtritto

**Comment by OOCAZ** [comment]
Did some more testing and the import appears to be broken...
importError

**Comment by OOCAZ** [comment]
Did some more testing and the import appears to be broken...
importError

**Comment by OOCAZ** [comment]
Would like some help with this @rtritto @BlackthornYugen, I can't tell if my local DB is broken, or if this commit breaks the capability to import

**Comment by BlackthornYugen** [comment]
> Would like some help with this @rtritto @BlackthornYugen, I can't tell if my local DB is broken, or if this commit breaks the capability to import

Will try to test this evening

**Comment by rtritto** [comment]
> Would like some help with this @rtritto @BlackthornYugen, I can't tell if my local DB is broken, or if this commit breaks the capability to import

That import problem is on master too. This PR can be merged.

**Review by rtritto — APPROVED** [review]
> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981)* status: all files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen and @OOCAZ)

**Review by rtritto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981)* status: all files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen)

*[a discussion](https://reviewable.io/reviews/mongo-express/mongo-express/981#-NCRO8346skUOuiyzGcM:-NCe9Nrn94ZIXJSoo1ct:bb6un1j) (no related file):*
<details><summary><i>Previously, OOCAZ wrote…</i></summary><blockquote>

yes and no, I thought it was just built in, but apparently not, found an npm based library that is used in almost everything else: https://www.npmjs.com/package/escape-html I will change the function if someone else can handle the yarnfile when I get the function change pushed
</blockquote></details>

Done

___
___
*[`lib/routes/collection.js` line 535 at r3](https://reviewable.io/reviews/mongo-express/mongo-express/981#-NCRdjLV5iSXgFDNtS8t:-NCe95dtCSlJdmsyiNkw:bb6un1j) ([raw file](https://github.com/mongo-express/mongo-express/blob/438f5339d8c116cb76e4356342b596851066ed62/lib/routes/collection.js#L535)):*
<details><summary><i>Previously, BlackthornYugen (John Steel) wrote…</i></summary><blockquote>

Can we import the whole namespace? Or import it as escapeHtml? Encode isn't very descriptive.
</blockquote></details>

Done

**Review by shakaran — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981#-:-NCeBzQfCFuBPJCte5yR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BlackthornYugen)

**Comment by shakaran** [comment]
> > Would like some help with this @rtritto @BlackthornYugen, I can't tell if my local DB is broken, or if this commit breaks the capability to import
> 
> The import problem is on master too. This PR can be merged.

Please, open a new issue for address that POST error 500 in import

**Review by BlackthornYugen — COMMENTED** [review]
Thanks for verifying that. I was having some configuration issues myself I didn't have time to sort through. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981#-:-NCeFIOG-v9B59r92PBD:b-4fbjoq)* status: all files reviewed, 2 unresolved discussions (waiting on @OOCAZ)

**Review by BlackthornYugen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/981#-:-NCeFjkA9Mc4ZDXwSG1Q:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @OOCAZ)

**Pull request merged**
