### PR TITLE
Remove y18n from dependabot

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/982)
- - -

Current version of `y18n` is _5.0.8_, so remove ignore versions _4.0.1_ and _4.0.2_ from _dependabot_.

### CODE REVIEW

**Review by BlackthornYugen — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/982)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shakaran)

**Review by BlackthornYugen — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/982#-:-NCRS3FH3-FOtwn8SlSn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @shakaran)

**Comment by shakaran** [comment]
@rtritto @BlackthornYugen before to merge (already) did you test if breaks yargs or something with commander?

**Comment by BlackthornYugen** [comment]
> @rtritto @BlackthornYugen before to merge (already) did you test if breaks yargs or something with commander?

This change is just to stop ignoring an old version. I don't think any testing is required?

**Pull request merged**
