### PR TITLE
Set package-ecosystem to yarn in Dependabot

### LINKED ISSUE #930: Update version or settings of `dependabot`
Commits of `dependabot` should update latest version in _package.json_ and _yarn.lock_.

Example:

## Actural result
`package.json`
```diff
---
"devDependencies": {
    "@babel/core": "^7.16.0",
---
```

`yarn.lock`
```diff
---
  "@babel/core@^7.16.0":
-    version "7.16.0"
+    version "7.19.0"
---
```

## Expect result
`package.json`
```diff
---
"devDependencies": {
-    "@babel/core": "^7.16.0",
+    "@babel/core": "^7.19.0",
---
```

`yarn.lock`
```diff
---
-  "@babel/core@^7.16.0":
-    version "7.16.0"
+  "@babel/core@^7.19.0":
+    version "7.19.0"
---
```

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/945)
- - -

Fix #930

### CODE REVIEW

**Comment by shakaran** [comment]
Is it possible have both (npm and yarn) for dependabot?

**Comment by rtritto** [comment]
> Is it possible have both (npm and yarn) for dependabot?

I think you can add another item under _updates_. Anyway this project should only use _yarn_ for the _yarn.lock_ file.

**Comment by rtritto** [comment]
@shakaran @BlackthornYugen can we merge this? Just to check on new dependency update if it's works.

**Review by BlackthornYugen — APPROVED** [review]
Yup

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/945#-:-NBdAQ4H6-d2NlwSepIX:b2nhtan)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rtritto)

**Comment by BlackthornYugen** [comment]
I can't test anything for a few days. Moving on Monday. Only have my phone. If it needs testing I can't help with that. 😅

**Comment by BlackthornYugen** [comment]
If it breaks dependabot we can easily roll back so I'd say let's try it

**Pull request merged**
