### PR TITLE
chore: update Express.js to v5

### PR DESCRIPTION
**Pull request by rtritto**
This change is [Reviewable](https://reviewable.io/reviews/mongo-express/mongo-express/921)
- - -

[Migrate to v5](https://expressjs.com/en/guide/migrating-5.html)

### CODE REVIEW

**Comment by rtritto** [comment]
Correctly rebased with _master_.
FYI @shakaran

**Comment by shakaran** [comment]
> Correctly rebased with _master_. FYI @shakaran

it seems that still fail for the pipelines

**Comment by rtritto** [comment]
> > Correctly rebased with _master_. FYI @shakaran
> 
> it seems that still fail for the pipelines

I know, that fix works only with express v5.
My original idea is to wait a stable/rc express v5 to update the dependency. By this way, we should have less conflicts with rebases/synch.

**Comment by shakaran** [comment]
@rtritto this need rebase or update maybe

**Comment by shakaran** [comment]
@rtritto any update with this?

**Comment by rtritto** [comment]
v5 isn't updated with v4. Before merge, I would wait for the v5 to become stable.
`express` seems not mantained so we should consider to migrate to `fastify`. I did this branch https://github.com/mongo-express/mongo-express/tree/fastify-migration as draft.

**Comment by shakaran** [comment]
> v5 isn't updated with v4. Before merge, I would wait for the v5 to become stable. `express` seems not mantained so we should consider to migrate to `fastify`. I did this branch https://github.com/mongo-express/mongo-express/tree/fastify-migration as draft.

In that versión, I see that we lost the support for swigEngine, could you add it too and make a PR rebased?

**Comment by rtritto** [comment]
Seems that this changes isn't need anymore with current v5.

Replaced with #1630

**Pull request closed without merging**
